### ISSUE TITLE
可不可以只加密文档，而不加密整改笔记本

### ISSUE THREAD

**Issue by hopana** [kuangdongksk/siyuan-access-controller#16]
经常有这样的需求：
- 笔记中，某个笔记内容可能有敏感信，想仅针对这个笔记文档加密；
- 而不用加密整个笔记本！（造成整个笔记本其他文件需要解密才能看到，很麻烦）

因此，能优化一下：兼容仅加密单个文档吗？

**Comment by kuangdongksk** [comment]
到了文档层面就是块的层级，要考虑的事情比较多，最近都没空开发

**Comment by hopana** [comment]
> 到了文档层面就是块的层级，要考虑的事情比较多，最近都没空开发

不是，我的意思不是块，是单个文档，也就是单个的笔记，不是笔记本。其实我想自己实现，但是你的代码里很多都是中文，哈哈哈，搞起来有点蛋疼🤣

**Comment by kuangdongksk** [comment]
其实要做的事情不太多，主要的实现思路是添加一个蒙层遮住内容，这个蒙层的逻辑已经有了现在就是要开发添加蒙层的逻辑
建议使用属性来进行标识，监听在加载时是否有对应的属性
中文的话是为了方便看懂，可以使用vscode的重命名符号来进行全局替换
这个项目之后很可能被废弃，写的太烂了

**Comment by kuangdongksk** [comment]
这玩意太难改了，放弃

**Comment by kuangdongksk** [comment]
> 经常有这样的需求：
> 
> * 笔记中，某个笔记内容可能有敏感信，想仅针对这个笔记文档加密；
> * 而不用加密整个笔记本！（造成整个笔记本其他文件需要解密才能看到，很麻烦）
> 
> 因此，能优化一下：兼容仅加密单个文档吗？

可以看看这个[喧嚣插件 - 访问控制功能](https://ld246.com/article/1734947243187)
